// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN30qeljRYoiPqqH0kuJCG6GuQx1TzaTg',
    appId: '1:673506589751:web:7fe83cac872f3a5233d3b2',
    messagingSenderId: '673506589751',
    projectId: 'bijoutery-76e19',
    authDomain: 'bijoutery-76e19.firebaseapp.com',
    storageBucket: 'bijoutery-76e19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-Xgr-KJe-Tz7Fx7QpfUqFvm_flF0Ty0o',
    appId: '1:673506589751:android:7fe83cac872f3a5233d3b2',
    messagingSenderId: '673506589751',
    projectId: 'bijoutery-76e19',
    storageBucket: 'bijoutery-76e19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Xgr-KJe-Tz7Fx7QpfUqFvm_flF0Ty0o',
    appId: '1:673506589751:ios:7fe83cac872f3a5233d3b2',
    messagingSenderId: '673506589751',
    projectId: 'bijoutery-76e19',
    storageBucket: 'bijoutery-76e19.appspot.com',
    iosBundleId: 'com.example.anotacoes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-Xgr-KJe-Tz7Fx7QpfUqFvm_flF0Ty0o',
    appId: '1:673506589751:macos:7fe83cac872f3a5233d3b2',
    messagingSenderId: '673506589751',
    projectId: 'bijoutery-76e19',
    storageBucket: 'bijoutery-76e19.appspot.com',
    iosBundleId: 'com.example.anotacoes',
  );
}
